EconomicManagementAPP/Controllers/AccountTypesController.cs
using EconomicManagementAPP.Models;
using Microsoft.AspNetCore.Mvc;
using EconomicManagementAPP.Interface;

namespace EconomicManagementAPP.Controllers
{
    public class AccountTypesController : Controller
    {
        private readonly IRepositorieAccountTypes repositorieAccountTypes;
        private readonly IRepositorieUsers repositorieUsers;

        public AccountTypesController(IRepositorieAccountTypes repositorieAccountTypes, IRepositorieUsers repositorieUsers)
        {
            this.repositorieAccountTypes = repositorieAccountTypes;
            this.repositorieUsers = repositorieUsers;
        }

        public async Task<IActionResult> Index()
        {
            if (UsersController.valorSesion is null)
            {
                return RedirectToAction("Login", "Users");
            }
            var userId = UsersController.valorSesion.Id;
            
            var accountTypes = await repositorieAccountTypes.GetAccountsTypes(userId);
            return View(accountTypes);
        }
        public IActionResult Create()
        {
            if (UsersController.valorSesion is null)
            {
                return RedirectToAction("Login", "Users");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AccountTypes accountTypes)
        {
            if (!ModelState.IsValid)
            {
                return View(accountTypes);
            }

            accountTypes.UserId = UsersController.valorSesion.Id; ;
            accountTypes.OrderAccount = 1;

            // Validamos si ya existe antes de registrar
            var accountTypeExist =
               await repositorieAccountTypes.Exist(accountTypes.Name, accountTypes.UserId);

            if (accountTypeExist)
            {

                ModelState.AddModelError(nameof(accountTypes.Name),
                    $"The accountTypes {accountTypes.Name} already exist.");

                return View(accountTypes);
            }
            accountTypes.DbStatus = true;
            int newId = await repositorieAccountTypes.Create(accountTypes);
            return RedirectToAction("Create", "Accounts", new { id = newId });
        }

        // Hace que la validacion se active automaticamente desde el front
        [HttpGet]
        public async Task<IActionResult> VerificaryAccountType(string Name)
        {
            var userId = UsersController.valorSesion.Id;
            var accountTypeExist = await repositorieAccountTypes.Exist(Name, userId);

            if (accountTypeExist)
            {
                // permite acciones directas entre front y back
                return Json($"The accountTypes {Name} already exist");
            }

            return Json(true);
        }

        //Actualizar
        [HttpGet]
        public async Task<ActionResult> Modify(int id)
        {
            if (UsersController.valorSesion is null)
            {
                return RedirectToAction("Login", "Users");
            }
            var userId = UsersController.valorSesion.Id;
            var accountType = await repositorieAccountTypes.GetAccountById(id, userId);

            if (accountType is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(accountType);
        }
        [HttpPost]
        public async Task<ActionResult> Modify(AccountTypes accountTypes)
        {
            var userId = UsersController.valorSesion.Id;
            var accountType = await repositorieAccountTypes.GetAccountById(accountTypes.Id, userId);

            if (accountType is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieAccountTypes.Modify(accountTypes);// el que llega
            return RedirectToAction("Index", "Home");

        }
        // Eliminar
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (UsersController.valorSesion is null)
            {
                return RedirectToAction("Login", "Users");
            }
            var userId = UsersController.valorSesion.Id;
            var account = await repositorieAccountTypes.GetAccountById(id, userId);

            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            account.NumberAccount = await repositorieAccountTypes.GetNumberAccount(id);

            return View(account);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteAccount(int id)
        {
            var userId = UsersController.valorSesion.Id;
            var account = await repositorieAccountTypes.GetAccountById(id, userId);

            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            var account_Type = await repositorieAccountTypes.ExistingAccountType(id);

            if (account_Type == false)
            {
                await repositorieAccountTypes.Delete(id);
                return RedirectToAction("Index", "Home");
            }

            await repositorieAccountTypes.DeleteModify(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

EconomicManagementAPP/Views/Shared/_Layout.cshtml
@using EconomicManagementAPP.Controllers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-appd-version="true" />
    <link rel="stylesheet" href="~/css/AccorddionStyles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EconomicManagementAPP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <title >  @ViewData["title"] - EconomicManagementAPP</title>
     
</head>
<body class="bodyGen">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 bodyGen">
            <div class="container-fluid">
                <a class="navbar-brand titles" asp-area="" asp-controller="Home" asp-action="Index">EconomicManagementAPP</a>
                <span class="spacer"></span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (UsersController.valorSesion is not null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark titles" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                
                                <a class="nav-link text-dark titles" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                            
                                <a class="nav-link text-dark titles" asp-area="" asp-controller="Transactions" asp-action="IndexAll">See All Transactions</a>
                            </li>
                            <span class="headerSpacer"></span>
                            <li class="nav-item">
                                <a class="nav-link text-dark titles" asp-area="" title="DeleteUser" asp-controller="Users" asp-action="Delete">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z" />
                                    </svg>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark titles" asp-area="" title="Modify" asp-controller="Users" asp-action="Modify">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-wrench-adjustable" viewBox="0 0 16 16">
                                        <path d="M16 4.5a4.492 4.492 0 0 1-1.703 3.526L13 5l2.959-1.11c.027.2.041.403.041.61Z" />
                                        <path d="M11.5 9c.653 0 1.273-.139 1.833-.39L12 5.5 11 3l3.826-1.53A4.5 4.5 0 0 0 7.29 6.092l-6.116 5.096a2.583 2.583 0 1 0 3.638 3.638L9.908 8.71A4.49 4.49 0 0 0 11.5 9Zm-1.292-4.361-.596.893.809-.27a.25.25 0 0 1 .287.377l-.596.893.809-.27.158.475-1.5.5a.25.25 0 0 1-.287-.376l.596-.893-.809.27a.25.25 0 0 1-.287-.377l.596-.893-.809.27-.158-.475 1.5-.5a.25.25 0 0 1 .287.376ZM3 14a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z" />
                                    </svg>
                                </a>
                            </li>
                            <li class="nav-item">
                                @*apuntamos al controller asp-controller="AccountTypes" y al view asp-action="Index"*@
                                <a class="nav-link text-dark titles" asp-area="" asp-controller="Users" asp-action="LogOut">Log Out</a>
                            </li>
                        }
                        else
                        {
                            <span class="headerSpacer"></span>
                            <li class="nav-item">
                                @*apuntamos al controller asp-controller="AccountTypes" y al view asp-action="Index"*@
                                <a class="nav-link text-dark titles" asp-area="" asp-controller="Users" asp-action="Create">Sign up</a>
                            </li>
                            <li class="nav-item">
                                @*apuntamos al controller asp-controller="AccountTypes" y al view asp-action="Index"*@
                                <a class="nav-link text-dark titles" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container titles">
            &copy; 2022 - Developed by JulyMorales22
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>